[tool.poetry]
name = "feeder"
version = "0.0.1"
description = "Make RSS great again"
authors = ["9seconds <nineseconds@yandex.ru>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.10.0"
itemloaders = "^1.1.0"
w3lib = "^2.1.2"
dateparser = "^1.1.8"
lxml = "^4.9.3"
scrapy-fake-useragent = "^1.4.4"

[tool.black]
line-length = 80
target-version = ["py311"]

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
flake8 = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
