#!/bin/bash

if [[ ! -v BASE_URL ]]; then
  echo "Base URL is not defined" 1>&2
  exit 1
fi

OUT="$(mktemp -d)"
trap 'rm -rf -- "$OUT"' EXIT

crawl "$OUT" 2>&1 | tee -a "/var/log/feeder/crawl-$(date -u +%F).log"
generate_opml "$BASE_URL" "$PASSWORD" > "$OUT/index.opml"
zopfli --i1000 $OUT/*
rm -rf /feeds/*
mv $OUT/* /feeds/
