#!/bin/bash

if [[ ! -v BASE_URL ]]; then
  echo "Base URL is not defined" 1>&2
  exit 1
fi

command do generate nginx > /etc/nginx/nginx.conf
if [[ ! -f "$AARON_FEEDS_DIR/index.opml" ]]; then
  echo "Fresh installation, run first crawl. This can take a while..."
  collect
  command do generate opml > "$AARON_FEEDS_DIR/index.opml"
  echo "Done."
fi

exec runsvdir /runit
