#!/bin/bash

if [[ ! -v AARON_BASE_URL ]]; then
  echo "Base URL is not defined" 1>&2
  exit 1
fi

command do generate nginx > /etc/nginx/nginx.conf
command do generate opml > /tmp/index.opml

touch -a "$AARON_FEEDS_DIR/index.opml"
if ! cmp -s /tmp/index.opml "$AARON_FEEDS_DIR/index.opml" >/dev/null 2>&1; then
  echo "Fresh installation, run first crawl. This can take a while..."
  collect
  mv /tmp/index.opml "$AARON_FEEDS_DIR/index.opml"
  echo "Done."
fi

exec runsvdir /runit
